version: "3.9"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    container_name: base_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  users:
    build:
      context: .
      dockerfile: Dockerfile.users
    container_name: users_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  products:
    build:
      context: .
      dockerfile: Dockerfile.products
    container_name: products_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db

  categories:
    build:
      context: .
      dockerfile: Dockerfile.categories
    container_name: categories_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db

  search:
    build:
      context: .
      dockerfile: Dockerfile.search
    container_name: search_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    depends_on:
      - db
      - elasticsearch

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    depends_on:
      - base

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

volumes:
  mysql_data: